### ISSUE TITLE
Weird crash after trying to edit textures in mod

### ISSUE THREAD

**Issue by TheSightSeer1948** [yanny7/YTech#15]
I retextured the bronze textures in the mod, and yet now every time I try to equip a piece of bronze armor, the game crashes and says " The game crashed whilst rendering entity in world
Error: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:textures/models/armor/Bronze_layer_2.png "

I made sure to not change the name at all, and the issue persists even after reinstalling the mod, forge, and even my entire game. I am unsure if this is something you'd know how to fix, however I had no idea where else to ask, as I am unsure if anybody has ever had this issue before

**Comment by TheSightSeer1948** [comment]
That's the part that confuses me though, because even when I changed the mod out with one I downloaded from curseforge, that had the original texture files, I still get this error.

**Comment by deftesthawk** [comment]
I just loaded the mod on its own to test this and it seems to crash the game when any armor from ytech is equipped. But when I tested it in my modpack it doesn’t crash the game, instead the armor is displayed blocky with purple and black textures.

**Comment by deftesthawk** [comment]
Looks like the issue dates back to YTech 0.7 as 0.6.1 doesn't have this issue

**Comment by TheSightSeer1948** [comment]
I see. Thank you for your help here, I guess I will be using version 6.1 until this is fixed

**Comment by yanny7** [comment]
Fixed in v0.9.1
