### ISSUE TITLE
Crash when rendering part of world + vanilla mobs spawning

### ISSUE THREAD

**Issue by deftesthawk** [yanny7/YTech#16]
I loaded up the game with only YTech installed, loaded a world then once I spawned in I traveled a certain direction and the game crashed. I reloaded the game and tried multiple times to see if it was a one off but it kept happening, same error every time.

Seed and location info if needed:
-3726660425880647472
After you spawn in fly straight up you will see a village in one of the directions fly towards/past it and the game will crash 
(you might have to fly around the village area as one of my tests it didn't crash until I did this)

[crash log.txt](https://github.com/user-attachments/files/17907504/crash.log.txt)

**Comment by yanny7** [comment]
Fixed in v0.9.2
