### ISSUE TITLE
Offer

### ISSUE THREAD

**Issue by Ikyripes** [yanny7/ytech#20]
Can I somehow remove the mod's ore?
(Without rewriting the code)
Something like spawn ore true/false

**Comment by Ikyripes** [comment]
Pls

**Comment by deftesthawk** [comment]
You can do that using other mods, here's a reddit post with 2 different methods
https://www.reddit.com/r/feedthebeast/comments/1epz41m/how_to_remove_ore_gen_with_kubejs/

I need to do this for my modpack as well, so if you struggle getting it working I can send you my kubejs script once I get around to it.

**Comment by Ikyripes** [comment]
It would be great. I also wanted to play this in KubeJS, but they haven't updated the event world for Minecraft 1.20.1

**Comment by deftesthawk** [comment]
- Install KubeJS 
- Download and extract the zip attached
- Place the script you just extracted in 'modpack\kubejs\startup_scripts' folder

If you want to disable any other ores just add them to the oreList
[ores_disable_startup.zip](https://github.com/user-attachments/files/18229627/ores_disable_startup.zip)

**Comment by deftesthawk** [comment]
@yanny7 When testing this I couldn't find any of the nether ores added, I'm guessing they are disabled? It confused me because they still show up in JEI

**Comment by yanny7** [comment]
They are available for modpack makers, but not used in worldgen

**Comment by Ikyripes** [comment]
Best 
Thanks, very helpful
