### ISSUE TITLE
[Request] requiresCorrectToolForDrops config

### ISSUE THREAD

**Issue by guivnf** [yanny7/ytech#21]
Basically what the title says, i really want a config option that allows me to completely disable/change which blocks are affected by "requiresCorrectToolForDrops", i'm using ytech as a rough base for my modpack but i'm remaking every part of it's progression & not being able to collect dirt with bare hands makes the first night basically impossible to survive, so that's it :)

Minecraft: 1.20.1
Forge: 47.3.12
Ytech: 0.9.2

**Comment by yanny7** [comment]
Already available from 0.9.0, please check [wiki](https://github.com/yanny7/YTech/wiki/Configuration):

block tag ytech:require_valid_tool - require on these blocks valid tool
