### ISSUE TITLE
Hammers, saws and files have no durability

### ISSUE THREAD

**Issue by ElRichiRicon** [yanny7/YTech#5]
NeoForge 47.1.104 / 1.20.1
YTech 0.3.0
   (also tested in 0.3.1)

Also JEI 15.3.0.4

Most noticeable when crafting plates, the hammers are consumed. And they can be stacked
![image](https://github.com/yanny7/YTech/assets/45831667/fcf88ab5-2d8f-459b-b86e-13589d52fb5a)

**Comment by yanny7** [comment]
Fixed in 0.3.2
