### ISSUE TITLE
Crash with Caupona

### ISSUE THREAD

**Issue by Demosthenes178** [yanny7/YTech#6]
Placing YTechs aqueducts against each other with [Caupona](https://github.com/TeamMoegMC/Caupona) installed crashes the game to desktop. I'm not sure if this is an issue on Caupona's end or YTechs.

To reproduce:
1. Install YTech 1.20.1-0.4.0 and Caupona 1.20.1-0.4.9
2. Place YTech's aqueducts against each other (by right clicking on the side of an aqueduct with another aqueduct).

https://pastebin.com/23UmvMKC

**Comment by yanny7** [comment]
Fixed in 1.20.1-0.4.2
