### ISSUE TITLE
About crafting workspace

### ISSUE THREAD

**Issue by Sigmenzzz** [yanny7/YTech#9]
Version: ytech-1.21.1-0.7.1
I can only assemble it with hammer but not sharp hint, which make it hard to continue the game.

**Comment by Sigmenzzz** [comment]
I'm sure, here is screenshot in game:
![屏幕截图 2024-11-13 161051](https://github.com/user-attachments/assets/50dbc0b3-f301-46d8-b3ac-6899f6d19d17)
In fact, when I right-click it with sharp hint, the sharp hint will be inserted in crafting workspace, like this:
![屏幕截图 2024-11-13 161422](https://github.com/user-attachments/assets/10673e15-a412-4792-80b7-753e8c9654c0)

**Comment by yanny7** [comment]
![image](https://github.com/user-attachments/assets/e77c3b8c-61b8-41be-91e5-944b6e8d7721)

I downloaded latest 0.7.1 from curseforge and it's working as expected (hammer is accepted item, sharp flint isn't)

**Comment by Sigmenzzz** [comment]
well, my game version is 1.21, not 1.20

**Comment by yanny7** [comment]
Sorry man, I missed that

**Comment by yanny7** [comment]
FIxed in 0.8.0
